<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
  <? if ($logged_in): ?>
    <div>
      <h1>Hello <?=$user->name; ?></h1>
      <p><a href="/logout" class="btn">Sign out</a></p>
    </div>
  <? endif; ?>
  <? if (! $logged_in): ?>
    <p>
      <a href="https://github.com/login/oauth/authorize?login&client_id=<?=$client_id;?>" class="btn">Sign in with GitHub</a>
    </p>
  <? endif; ?>
</body>
</html>